name: "Deploy with github openid"

on:
  push:
    branches:
      - main

env:
  TF_LOG: INFO
  AWS_REGION: us-east-1
  ROLE_SESSION_NAME: deploy-test
  ROLE_ARN: arn:aws:iam::517171444774:role/repo-github-openid-aws-deploy
  TF_VAR_github_run_number: ${{ github.run_number }}
  TERRAFORM_VERSION: 1.3.0
  TERRAFORM_DESTROY: false

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          role-session-name: ${{ env.ROLE_SESSION_NAME }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: Terraform init
        id: init
        run: terraform init --upgrade
      - name: Terraform format
        id: fmt
        run: terraform fmt -check
      - name: Terraform validate
        id: validate
        run: terraform validate
      - name: Terraform Apply
        id: apply
        if: ${{ env.TERRAFORM_DESTROY == 'false' }}
        run: terraform apply -auto-approve -input=false
      - name: Terraform Apply Destroy
        id: apply-destroy
        if: ${{ env.TERRAFORM_DESTROY == 'true' }}
        run: terraform destroy -auto-approve -input=false
